name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Start
      run: echo Start
    - name: Slow
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        for ((i=1;i<=200;i++)); do
        echo $i
        sleep 1
        done
    - name: End
      run: echo Done